services:
  # Frontend (React/Vite)
  frontend:
    build:
      context: ./Frontend/project
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000/api
      - VITE_PYTHON_API_URL=http://localhost:8001/api/v1
    depends_on:
      - backend
      - python-server
    networks:
      - app-network

  # Backend (Node.js/Express)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.node
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/interviewai
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=http://localhost:3000
      - PYTHON_API_URL=http://python-server:8001
    depends_on:
      - mongo
    networks:
      - app-network
    volumes:
      - ./backend/uploads:/app/uploads

  # Python Server (FastAPI)
  python-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
    networks:
      - app-network
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/reports:/app/reports

  # MongoDB Database
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=interviewai
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge