version: '3.8'

services:
  # Main application
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/video_analysis_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - STORAGE_TYPE=local
      - DEBUG=True
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./reports:/app/reports
    depends_on:
      - db
      - redis
    networks:
      - video-analysis-network

  # PostgreSQL database
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=video_analysis_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - video-analysis-network

  # Redis for caching and task queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - video-analysis-network

  # Celery worker for background tasks
  worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/video_analysis_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./reports:/app/reports
    depends_on:
      - db
      - redis
    networks:
      - video-analysis-network

  # Celery beat for periodic tasks
  beat:
    build: .
    command: celery -A app.celery_app beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/video_analysis_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./reports:/app/reports
    depends_on:
      - db
      - redis
    networks:
      - video-analysis-network

volumes:
  postgres_data:
  redis_data:

networks:
  video-analysis-network:
    driver: bridge
